# Generated by Django 3.0.2 on 2020-01-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataSolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField()),
                ('hourly', models.TimeField()),
                ('voltage', models.FloatField()),
                ('currents', models.FloatField()),
                ('power', models.FloatField()),
                ('temp', models.IntegerField()),
                ('intensity', models.IntegerField()),
            ],
        ),
    ]
